---
# The purpose of this is to pick up some data
# from files passed by Terraform
# could probably be done better

- name: Fetch Consul IP address
  shell: cat /opt/consul/server-addr
  register: fetch_consul_ip_address

- name: Fetch Consul server number
  shell: cat /opt/consul/server-count
  register: fetch_consul_bootstrap_expect

- name: Fetch datacenter name
  shell: cat /opt/consul/datacenter
  register: fetch_consul_datacenter

- name: Fetch public hostname
  shell: curl http://169.254.169.254/latest/meta-data/public-hostname
  register: fetch_public_host
