---
- hosts: all
  sudo: true
  pre_tasks:
  - set_fact:
      ansible_distribution_major_version: "6"
      nginx_user: nginx
  vars:
    consul_use_upstart: false
    consul_use_initd: true
    consul_version: 0.6.4
    consul_is_server: true
    consul_join_at_start: true
    consul_servers: ['{{ fetch_consul_ip_address.stdout }}']
    consul_client_address: "{{ ansible_default_ipv4['address'] }}"
    consul_bind_address: "{{ ansible_default_ipv4['address'] }}"
    consul_bootstrap_expect : "{{ fetch_consul_bootstrap_expect.stdout }}"
    consul_node_name: "{{ ansible_default_ipv4['address'] }}"
    consul_datacenter: "{{ fetch_consul_datacenter.stdout }}"

    consul_is_ui: true
#    consul_ui_server_name: "{{ fetch_public_host.stdout }}"

    consul_install_consulate: true
    consul_install_dnsmasq: true
#    consul_install_consul_cli: true

  roles:
    - init
    - savagegus.consul
